title: Top Daily Documents
description: Sends a daily email or Slack alert for the top 5 most viewed documents on DocumentCloud in the last 24 hours. 
type: object
properties:
  slack_webhook:
      title: Slack Webhook
      type: string
      format: uri
      description: Enter a slack webhook to enable Slack notifications
categories: 
  - statistics
version: 2
eventOptions:
  name: alert
  events:
    - daily